import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"; // নেভিগেশনের জন্য Link ইম্পোর্ট করলাম
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/CartContext";
import CartDrawer from "@/components/CartDrawer";
import { Toaster } from "react-hot-toast";
// ফন্ট সেটআপ (Next.js এর ডিফল্ট)
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

// সাইটের টাইটেল এবং ডেসক্রিপশন (SEO এর জন্য ভালো)
export const metadata: Metadata = {
  title: "SESTONE | Premium Streetwear",
  description: "Shop the best oversized t-shirts and streetwear at SESTONE.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased bg-gray-50 text-gray-900`}
      >
          
        <div className="min-h-screen bg-orange">
          <CartProvider>
            <Navbar />
            <CartDrawer />
            <Toaster position="top-center" reverseOrder={false}/>
            {children}
            
          </CartProvider>
        </div>

        {/* Simple Footer */}
        <footer className="bg-white border-t py-10 mt-20 text-center">
          <p className="text-sm text-gray-500">
            © {new Date().getFullYear()} SESTONE. Built with Passion.
          </p>
        </footer>
      </body>
    </html>
  );
}














// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ 
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Navbar />
//           {children}
//       </body>
//     </html>
//   );
// }
